add RegFragment
grishaster80/YouTrader pull request #15
Opened 2021-11-09 17:03 UTC by gagask

2021-11-09 17:49 UTC, grishaster80 requested changes
Найс!
Только строчки вынести в xml'ку

2021-11-09 17:49 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/ui/auth/RegFragment.kt
> +            buttonSign.text = "Зарегистрироваться"
Лучше все эти строки в `strings.xml` положить и прокидывать их напрямую в лэйаут

2021-11-09 19:42 UTC, gagask commented on app/src/main/java/com/technopark/youtrader/ui/auth/RegFragment.kt
> +            buttonSign.text = "Зарегистрироваться"
Хорошо

2021-11-10 08:30 UTC, grishaster80 approved these changes

2021-11-10 08:30 UTC, merged