Feature/retrofit call adapter
grishaster80/YouTrader pull request #19
Opened 2021-11-15 13:24 UTC by backtoroots

2021-11-15 14:15 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/network/CryptoCurrencyNetworkService.kt
> +        GlobalScope.launch {
Стоит убрать отсюда `GlobalScope.launch` и `CoroutineScope` объявлять во viewModel, с помощью `viewModelScope.launch`

2021-11-15 14:16 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/network/NetworkResponse.kt
> +    data class NetworkError(val error: IOException) : NetworkResponse<Nothing>()
Не понятно почему `NetworkError ` - это всегда `IOException `. Или это для примера?

2021-11-15 14:18 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/network/retrofit/NetworkResponseAdapterFactory.kt
> +            "Response must be parameterized as NetworkResponse<Foo> or NetworkResponse<out Foo>"
Текст в константы

2021-11-15 14:18 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/network/retrofit/NetworkResponseAdapterFactory.kt
> +            "return type must be parameterized as Call<NetworkResponse<<Foo>> or Call<NetworkResponse<out Foo>>"
Текст в константы

2021-11-16 08:02 UTC, backtoroots commented on app/src/main/java/com/technopark/youtrader/network/NetworkResponse.kt
> +    data class NetworkError(val error: IOException) : NetworkResponse<Nothing>()
На моем устройстве, когда нет интернета, пробрасывается `UnknownHostException`, которая наследуется от `IOException`. Код отлавливания ошибки в `NetworkResponseCall `в методе `onFailure`
```
val networkResponse = when (throwable) {
                        is IOException -> NetworkResponse.NetworkError(throwable)
                        else -> NetworkResponse.UnknownError(throwable)
                    }
```
не знаю, могут ли быть другие exception из-за отсутствия инета
Если других нет, то предлагаю:
1. Либо отлавливать только `UnknownHostException` и пробрасывать только его в `NetworkResponse.NetworkError`
2. Либо оставить как есть, чтобы показать, что это пробрасываемый exception наследуется от `IOException`
3. Либо расширить `NetworkResponse.NetworkError` и пробрасывать любой exception

2021-11-19 08:29 UTC, grishaster80 requested changes

2021-11-19 08:29 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/repository/CryptoCurrencyRepository.kt
> +    suspend fun getCurrencies(): NetworkResponse<Any> = withContext(Dispatchers.IO) {
Это точно не дело
`getCurrencies(): NetworkResponse<Any>`.

По идее отсюда должно торчать что-то типа `NetworkResponse<List<CryptoCurrency>>`, но точно не Any.

Если будут сложности - можно вот эту штуку посмотреть https://github.com/skydoves/Sandwich, либо найти какую-нибудь подобную в инете и адаптировать под наши нужды

2021-11-19 08:29 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/repository/CryptoCurrencyRepository.kt
> +        if (currenciesFromNetwork is NetworkResponse.Success) {
тут лучше `when` использовать для парсинга нашего `sealed` класса

2021-11-19 08:29 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/ui/currencies/CurrenciesFragment.kt
> +                            progressBar.visibility = View.GONE
Давай заведем файлик `ViewExt`, в который заведем extension функции для подобный штук
View.visible()
View.invisible()
View.gone()

И будем их юзать по проекту

2021-11-19 08:29 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/ui/currencies/CurrenciesViewModel.kt
> +            withContext(Dispatchers.Main) {
А зачем тут `Dispatchers.Main`?

2021-11-19 14:13 UTC, backtoroots commented on app/src/main/java/com/technopark/youtrader/ui/currencies/CurrenciesViewModel.kt
> +            withContext(Dispatchers.Main) {
Мне казалось, что если использовать Dispatchers.Main, то код будет выполняться в другой корутине, т.е. более оптимизированно

2021-11-19 14:15 UTC, backtoroots commented on app/src/main/java/com/technopark/youtrader/network/NetworkResponse.kt
> +    data class NetworkError(val error: IOException) : NetworkResponse<Nothing>()
Чтобы была возможность пробрасывать отсутствие интернета до вьюмодели, а оттуда через другой sealed class до UI

2021-11-19 14:17 UTC, backtoroots commented on app/src/main/java/com/technopark/youtrader/repository/CryptoCurrencyRepository.kt
> +    suspend fun getCurrencies(): NetworkResponse<Any> = withContext(Dispatchers.IO) {
Вопрос - нужно ли нам прокидывать NetworkResponse обобщенный до вьюмодели? Или только NetworkResponse.Success? Но тогда не понятно, зачем вообще кастомная обертка над Retrofit Response

2021-11-20 15:38 UTC, grishaster80 requested changes

2021-11-20 15:38 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/ui/currencies/CurrenciesViewModel.kt
> +            withContext(Dispatchers.Main) {
Это не так.
`viewModelScope` итак выполняется на `Dispatchers.Main` и `withContext(Dispatchers.Main)` тут означает - переложи код, выпоняемый на `Dispatchers.Main` на `Dispatchers.Main` - что не имеет никакого смысла

2021-11-20 15:38 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/repository/CryptoCurrencyRepository.kt
> +    suspend fun getCurrencies(): NetworkResponse<Any> = withContext(Dispatchers.IO) {
Тут я возможно запутал тебя первым ответом, сори(

Давай сделаем так, чтобы из репо торчал Flow.
Тут именно -  `Flow<List<CryptoCurrency>>`.

Вот тут статья с похожим примером - https://levelup.gitconnected.com/android-basic-app-using-mvvm-hilt-coroutines-flow-retrofit-and-coil-433763542ee0.

То есть будем прокидывать значение с серва, если оно пришло, в случае `NetworkResponse.*какая-нибудь_ошибка*` - можем пробрасывать исключение. Можем пробрасывать разные исключения в зависимости от того, какая именно ошибка в `NetworkResponse` - прокидывать ее во вьюмодель и в дальнейшем по разному отображать различные ошибки в UI. 

Сейчас не нужно заморачиваться с различными ошибками - можешь любое исключение пробросить в случае ошибки, отловить его в viewModel и отобразить на UI Toast'ом например.

2021-11-21 11:17 UTC, grishaster80 requested changes
nice!
Одну штучку поправить и вмержим

2021-11-21 11:17 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/ui/currencies/CurrenciesViewModel.kt
> +            try {
Тут не нужен `try/catch`
Заюзай просто `repository.getCurrencies().catch{}.collect{}` и в catch ошибки лови.

Это для консистентности делается. Раз уж с `Flow` работаем - будем отлавливать ошибки так, как принято при работе с `Flow`

2021-11-21 11:32 UTC, grishaster80 approved these changes

2021-11-21 11:32 UTC, merged