Api chart
grishaster80/YouTrader pull request #32
Opened 2021-11-25 13:53 UTC by Levichev

2021-11-30 15:59 UTC, grishaster80 requested changes

2021-11-30 16:03 UTC, Levichev commented on app/src/main/java/com/technopark/youtrader/model/CurrencyChartElement.kt
> +    val time: Long,
тут я назвал также как и в api ({"priceUsd":"19279.4659962293017969","time":1606953600000,"date":"2020-12-03T00:00:00.000Z"})

2021-11-30 16:05 UTC, Levichev commented on app/src/main/java/com/technopark/youtrader/model/CurrencyChartElement.kt
> +    val time: Long,
timetamp это вроде было время в которое обработался запрос, а time это уже время самой валюты

2021-12-01 07:55 UTC, grishaster80 approved these changes

2021-12-01 07:55 UTC, merged