History
grishaster80/YouTrader pull request #33
Opened 2021-11-28 18:13 UTC by Adefful

2021-11-29 13:51 UTC, grishaster80 requested changes
В целом хорошо.
Повыносить в константы, немного подправить viewModel и вмержим.
Если что пиши в чатик вопросики

2021-11-29 13:51 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/database/AppDatabase.kt
> +            // database.execSQL("INSERT INTO LocalCryptoCurrencyTransaction values(`1`,`BTC`,`Bitcoin`)")
Давай лучше эти строчки закоменченные удалим.
Или они нужны?
Если нужны отпиши хотя бы комментом в коде - зачем

2021-11-29 13:51 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/database/CryptoTransactionDao.kt
> +    suspend fun deleteCurrency(currency: LocalCryptoCurrencyTransaction)
2 метода с одинаковым названием - плохо выглядят.
Давай лучше что-нибудь типа `deleteCurrencyByTransaction` и `deleteCurrencyById`

2021-11-29 13:51 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/database/CryptoTransactionDao.kt
> +interface CryptoTransactionDao {
Конечно, плохо, что один репозиторий до такого числа методов разросся(
Но в текущих реалиях - это для нас не критично, пускай будет так

2021-11-29 13:51 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/model/HistoryOperationItem.kt
> +                opDate.text = timestampToFormatDate(transaction.timestamp.toLong(), "dd MMM yyyy")
Куда-нибудь в константы давай вынесем `"dd MMM yyyy"`

2021-11-29 13:51 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/model/HistoryOperationItem.kt
> +            if (transaction.amount > 0) {
Цифры и знаки в константы лучше)

2021-11-29 13:51 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/ui/currencies/InfoCurrencyFragment.kt
> +        val currencyId = arguments?.getString("currencyId")
В константы

2021-11-29 13:51 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/ui/currencies/InfoCurrencyFragment.kt
> +            currencyNameInfo.text = "Bitcoin"
Эти текста лучше будет в xml'ке проставить, чтобы количество строк кода в классе не увеличивать

2021-11-29 13:51 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/ui/currencies/InfoCurrencyFragment.kt
> +            { price -> binding.price.text = "$".plus(((price * 100000).roundToLong() / 100000.0).toString()) }
100000 лучше в константы с понятным названием, чтобы было понятно, что это за число

2021-11-29 13:51 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/ui/currencies/InfoCurrencyFragment.kt
> +                        binding.progressBar2.gone()
лучше конечно просто  `progressBar`, чем `progressBar2`

2021-11-29 13:51 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/ui/currencies/InfoCurrencyViewModel.kt
> +            repository.insertCurrency("1", "Bitcoin", "BTC")
Все эти `insertCurrency ` и `insertTransaction ` нужны в конечном варианте приложения тут?
Если нет и нужны только сейчас - оставь коммент плз про это.
Если вообще не нужны - лучше убрать

2021-11-29 13:51 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/ui/currencies/InfoCurrencyViewModel.kt
> +                curr ->
лучше `currency`, чем `curr `

2021-11-29 13:51 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/ui/currencies/InfoCurrencyViewModel.kt
> +            var sym: String = ""
`sym` - из названия не понятно, что лежит в переменной.

2021-11-29 13:51 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/ui/currencies/InfoCurrencyViewModel.kt
> +                    curr ->
currency

2021-11-29 13:51 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/ui/currencies/InfoCurrencyViewModel.kt
> +    val screenState: LiveData<Result<List<HistoryOperationItem>>> = _screenState
Тут наверное лучше сделать так, чтобы у тебя была одна LiveData `screenState`, которая бы содержала состояние экрана целиком.
Что-то типа `val screenState: LiveData<Result<InfoCurrencyScreenState>> = _screenState`

И внутри модельки `InfoCurrencyScreenState` будут различные поля, которыми интересуется фрагмент.
В том числе поля для `totalPrice `, `totalAmount `, `currency `. Тогда не придется тут писать вот эти 3 MutableLiveData.

В итоге во viewModel будет одна `private MutableLiveData`, которую мы обновляем во viewModel.
и одна `LiveData`, на которую подписывается фрагмент.(screenState у тебя так и устроен сейчас).

2021-11-29 16:45 UTC, Adefful commented on app/src/main/java/com/technopark/youtrader/database/AppDatabase.kt
> +            // database.execSQL("INSERT INTO LocalCryptoCurrencyTransaction values(`1`,`BTC`,`Bitcoin`)")
Тут я пытался добавить некоторые значения, чтобы они добалялись 1 раз. а не кажкдый раз при запуске.
Уберу

2021-11-29 16:49 UTC, Adefful commented on app/src/main/java/com/technopark/youtrader/ui/currencies/InfoCurrencyViewModel.kt
> +            repository.insertCurrency("1", "Bitcoin", "BTC")
Они нужны чтобы показать, что данные добавляются. Я могу убрать и добавить их при нажатии кнопки "Купить"

2021-12-01 10:16 UTC, Adefful commented
Есть ошибка. пытаюсь исправить

2021-12-01 11:56 UTC, Adefful commented
Вставка в БД нужна для того что показать, что работает. Потом когда портфель будет отображаться нормально это не нужно будет.

2021-12-01 14:29 UTC, grishaster80 requested changes
Поправить замечание во вьюмодели и смержим

2021-12-01 14:29 UTC, grishaster80 commented on app/src/main/java/com/technopark/youtrader/ui/currencies/InfoCurrencyViewModel.kt
> +            // TODO get current price from API
Кажется, что устанавливать значение _screenState.value в каждом из трёх collect'ов. Иначе может возникнуть ситуация, когда например выполнение метода getTotalAmount затянулось, а screenState.value = Result.Success(infoCurrencyModel) мы уже сделали и пользователь никогда не увидит актуальное состояние экрана. Если тут обращения к базе заменить на обращения в сеть сразу будет видно, что тут race condition

2021-12-02 16:12 UTC, Adefful commented
Все исправил

2021-12-05 07:57 UTC, grishaster80 approved these changes

2021-12-05 09:39 UTC, merged